In [1]:
import numpy as np
import random

In [95]:
# Crear dos matrices M1 y M2 de 10 x 10 con valores al azar en las diagonales y el resto de sus valores 5.
dimensiones=(10,10)
matrizOne = np.full(dimensiones,5)
for i in range(10):
    random = round(np.random.rand()*100)
    matrizOne[i][i]= random
acumulador = 9
for j in range(10):
    random = round(np.random.rand()*100)
    matrizOne[acumulador][j] = random
    acumulador -= 1
print("        [MATRIZ ONE]")
print(matrizOne)

        [MATRIZ ONE]
[[37  5  5  5  5  5  5  5  5 20]
 [ 5 79  5  5  5  5  5  5 92  5]
 [ 5  5 24  5  5  5  5 83  5  5]
 [ 5  5  5 28  5  5 33  5  5  5]
 [ 5  5  5  5 35 48  5  5  5  5]
 [ 5  5  5  5 48 67  5  5  5  5]
 [ 5  5  5 71  5  5 15  5  5  5]
 [ 5  5 24  5  5  5  5 70  5  5]
 [ 5 99  5  5  5  5  5  5 28  5]
 [26  5  5  5  5  5  5  5  5 65]]


In [94]:
dimensiones=(10,10)
matrizTwo = np.full(dimensiones,5)
for i in range(10):
    random = round(np.random.rand()*100)
    matrizTwo[i][i]= random
acumulador = 9
for j in range(10):
    random = round(np.random.rand()*100)
    matrizTwo[acumulador][j] = random
    acumulador -= 1
print("        [MATRIZ TWO]")
print(matrizTwo)

        [MATRIZ TWO]
[[50  5  5  5  5  5  5  5  5 45]
 [ 5 34  5  5  5  5  5  5 32  5]
 [ 5  5  5  5  5  5  5 35  5  5]
 [ 5  5  5 59  5  5 78  5  5  5]
 [ 5  5  5  5 39 45  5  5  5  5]
 [ 5  5  5  5 96 11  5  5  5  5]
 [ 5  5  5 19  5  5 89  5  5  5]
 [ 5  5 83  5  5  5  5 33  5  5]
 [ 5 57  5  5  5  5  5  5  6  5]
 [83  5  5  5  5  5  5  5  5 26]]


In [109]:
# •	Multiplicar las matrices M1 y M2 del ejercicio anterior y registrar el tiempo que demora en un archivo de texto llamado “resultado1.txt”
import time
start=time.time()
multiplicacion = np.dot(matrizOne,matrizTwo)
finish = ((time.time()-start)*1000)
print("     [RESULTADOS OBTENIDOS]")
print (f"[TIME OF THE  MULTIPLICATION]: {finish}")
print (f"[MATRIX OBTAINED]: \n {multiplicacion}")
print("[DO YOU WANT TO SAVE IT IN A FILE ?]")
option = input("[YES] OR [NO]: ")
if option.lower() == "yes":
    # Guardamos en un archivo
    with open('resultados1.txt', 'w') as resul:
        resul.write("[MULTIPLICATION RESULTS]\n")
        resul.write(f"[THE TIMES IS]:  {finish}\n")
        resul.write(f"[THIS IS THE MATRIX]: \n {multiplicacion}")
    print("[SAVE ARCHIV]")
else:
    print("[THANKS]")

     [RESULTADOS OBTENIDOS]
[TIME OF THE  MULTIPLICATION]: 0.16498565673828125
[MATRIX OBTAINED]: 
 [[3710  890  875  825 1110  715 1270  775  625 2385]
 [1670 8130 1445 1395 1680 1285 1840 1345 3280 1360]
 [1350 1140 7209 1075 1360  965 1520 3779  875 1040]
 [1120  910  895 2479 1130  735 5321  795  645  810]
 [1230 1020 1005  955 6173 2303 1400  905  755  920]
 [1390 1180 1165 1115 8504 3097 1560 1065  915 1080]
 [1245 1035 1020 4674 1255  860 7073  920  770  935]
 [1285 1075 6130 1010 1295  900 1455 3350  810  975]
 [1450 5162 1225 1175 1460 1065 1620 1125 3536 1140]
 [6895 1060 1045  995 1280  885 1440  945  795 3060]]
[DO YOU WANT TO SAVE IT IN A FILE ?]
[SAVE ARCHIV]


In [176]:
# •	Crear una matriz M3 de 10x10 con valores al azar en los bordes y el interior con ceros.
dimensiones = (10,10)
matrizThree = np.full(dimensiones,0)
# Fila 0 variacion el la columna
for i in range(10):
    matrizThree[0][i] = np.random.rand()*100
# Fila 9 variacion el la columna
for i in range(10):
    matrizThree[-1][i] = np.random.rand()*100
# Columna 0 variacion en las filas
for i in range(10):
    matrizThree[i][0] = np.random.rand()*100
 # Columna 9 variacion en las filas
for i in range(10):
    matrizThree[i][-1] = np.random.rand()*100
print("       [MATRIZ THREE]")
print(matrizThree)


       [MATRIZ THREE]
[[20 10 31 45 36 81 88 57 64 61]
 [66  0  0  0  0  0  0  0  0 25]
 [28  0  0  0  0  0  0  0  0  1]
 [16  0  0  0  0  0  0  0  0 98]
 [ 0  0  0  0  0  0  0  0  0 54]
 [19  0  0  0  0  0  0  0  0 52]
 [29  0  0  0  0  0  0  0  0 35]
 [38  0  0  0  0  0  0  0  0 46]
 [57  0  0  0  0  0  0  0  0 71]
 [78 51 25 98 25 38 69 40 28  7]]


In [303]:
# •	Crear una matriz M4 de 10x10 con ceros en los bordes y valores al azar en el interior.
dimensiones = (10,10)
matrizFour = np.full(dimensiones,0)
fila = 1
columna = 0
while(columna != 8):
    for i in range(8):
        matrizFour [i+1][fila] = np.random.rand()*100
    columna += 1
    fila += 1
print("       [MATRIZ FOUR]")
print(matrizFour)

       [MATRIZ FOUR]
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 84 24 86  6 48 41 79 83  0]
 [ 0  1 88 40 47 43 27  0  5  0]
 [ 0 38 35 67 23 30 62 35 73  0]
 [ 0 26 60 99 24 44 87 49 63  0]
 [ 0 75 38 37 67 87 39 43 97  0]
 [ 0 95 49 75  1  3 73 84 85  0]
 [ 0  9 33 53 70 49 11 60 85  0]
 [ 0 20  7 61 37 32 21 39 83  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [306]:
# •	Multiplicar las matrices M3 y M4 del ejercicio anterior y registrar el tiempo que demora en un archivo de texto llamado “resultado2.txt”
import time
start=time.time()
multiplicacion = np.dot(matrizThree,matrizFour)
finish = ((time.time()-start)*1000)
print("     [RESULTADOS OBTENIDOS]")
print (f"[TIME OF THE  MULTIPLICATION]: {finish}")
print (f"[MATRIX OBTAINED]: \n {multiplicacion}")
print("[DO YOU WANT TO SAVE IT IN A FILE ?]")
option = input("[YES] OR [NO]: ")
if option.lower() == "yes":
    # Guardamos en un archivo
    with open('resultados2.txt', 'w') as resul:
        resul.write("[MULTIPLICATION RESULTS]\n")
        resul.write(f"[THE TIMES IS]:  {finish}\n")
        resul.write(f"[THIS IS THE MATRIX]: \n {multiplicacion}")
    print("[SAVE ARCHIV]")
else:
    print("[THANKS]")

     [RESULTADOS OBTENIDOS]
[TIME OF THE  MULTIPLICATION]: 0.11110305786132812
[MATRIX OBTAINED]: 
 [[    0 19745 16422 25201 15289 16899 18723 20920 32032     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0 19008 14695 24836 10786 13932 18564 19606 28362     0]]
[DO YOU WANT TO SAVE IT IN A FILE ?]
[SAVE ARCHIV]


In [ ]:
# Realizar el conteo de las palabras que contiene el libro, no debe tomar en cuenta las palabras cortas, eliminar del conteo las palabras menores a cinco caracteres de longitud.
with open('3.- Proyecto G.txt', 'r', encoding='utf-8') as libro:
    text = libro.read()
words = np.array(text.lower().split())
total_words = len(words)
for palabra in words:
    if len(palabra) <= 5:
        total_words -= 1
print(f"El libro cuenta con alrededor de: {total_words} palabras, excluyendo las palbras menores a 5 letras")

El libro cuenta con alrededor de: 90423 palabras, excluyendo las palbras menores a 5 letras


In [312]:
# •	El resultado debe guardarse en un archivo de texto	 llamado resultado3.txt, dicho archivo debe contener: 
# Su apellido-nombre, el tiempo que demoró en realizar el conteo, el número de palabras y la frecuencia de palabras.
start=time.time()
with open('3.- Proyecto G.txt', 'r', encoding='utf-8') as file:
    text = file.read()
words = np.array(text.lower().split())
total_words = len(words)
letter = input("[INGRESE LA PALABRA A BUSCAR EN EL LIBRO]: ")
countFrecuencia = 0
for palabra in words:
    if len(palabra) <= 5:
        total_words -= 1
    if palabra == letter.lower():
        countFrecuencia += 1
finish = ((time.time()-start)*1000)
with open('resultados3.txt', 'w') as resultado3:
    resultado3.write("[ NUÑEZ ERICK (EJERCICIO LIBRO)]\n")
    resultado3.write(f"[TIME]: {finish}\n")
    resultado3.write(f"[NUMBER OF WORDS]: {total_words} words, excluyendo the words menores a 5 letras\n")
    resultado3.write(f"LA PALABRA [{letter}] APARECE: {countFrecuencia} veces\n")
print("Se a guardado tu archivo")

Se a guardado tu archivo
